Option Strict Off
Option Explicit On
Module OAPrompts
	'global settings
	Public Const MSGProperties As String = " Properties"
	Public Const MSGDone As String = "Done"
	Public Const MSGBrowse As String = "Browse"
	Public Const MSGok As String = "OK"
	Public Const MSGCancel As String = "Cancel"
	Public Const MSGSearch As String = "Search"
	Public Const MSGApply As String = "Apply"
	Public Const MSGClose As String = "Close"
	Public Const MSGNone As String = "None"
	Public Const MSGYes As String = "Yes"
	Public Const msgSave As String = "Save"
	Public Const msgOpen As String = "Open"
	Public Const MSGResults As String = "Search Results"
	Public Const MSGSize As String = "Size"
	Public Const MSGAdd As String = "ADD"
	Public Const msgRemove As String = "Remove"
	Public Const MSGNew As String = "New"
	Public Const msgImporting As String = "Importing"
	Public Const msgPage As String = "Page "
	Public Const msgOf As String = " of "
	Public Const msgSearchResults As String = "Search Results"
	Public Const msgProperty As String = " Property"
	Public Const msgDocument As String = "Document"
	Public Const msgDate As String = "Date"
	Public Const msgPrint As String = "Print"
	Public Const msgDatabase As String = "Database"
	Public Const msgAreYouSure As String = "Are you sure"
	Public Const msgFileDoesNotExist As String = "File Does Not Exist"
	Public Const MSGPropertyIndexer As String = "Property Indexer"
	Public Const msgScanInto As String = "Scan into "
	Public Const msgNewDB1 As String = "Warning: Database already exists"
	
	'sql form
	Public Const msgAPSPropertySearch As String = "Property Search"
	Public Const MSGSQLForm As String = "Property Search"
	Public Const MSGSQLCondition As String = "Condition"
	Public Const MSGSQLValue As String = "Value"
	Public Const MSGSQLAppend As String = "Append Search"
	Public Const MSGSQL001 As String = "The SQL statement is missing a text value string"
	Public Const MSGSQL002 As String = "The SQL statement is missing the field to search"
	Public Const MSGSQL00Z As String = "The SQL statement is missing the condition for search"
	Public Const MSGSQL003 As String = "no matches for"
	Public Const MSGSQL004 As String = "SQLSearch "
	Public Const MSGSQL005 As String = "Found "
	Public Const MSGSQL006 As String = "Document Hits of "
	Public Const MSGSQL007 As String = "You must enter the value in the form of 1/1/2000"
	'surround near search form
	Public Const MSGSNSForm As String = "Surround Near Search"
	Public Const MSGSNSProximity As String = "Proximity Searching"
	Public Const MSGSNSFind As String = "Find"
	Public Const MSGSNSWithin As String = "Within"
	Public Const MSGSNSWords_of As String = "Words of"
	'smart index form
	Public Const MSGSINDEXForm As String = "File Types to Index"
	Public Const MSGSINDEXSelect As String = "Select the File Types to Index"
	Public Const MSGSINDEXImageFiles As String = "Image Files"
	Public Const MSGSINDEXtif As String = "TIF Images"
	Public Const MSGSINDEXraster As String = "CALS Raster"
	Public Const MSGSINDEXcolor As String = "Color(ipg,gif)"
	Public Const MSGSINDEXCADFiles As String = "CAD Files"
	Public Const MSGSINDEXdwg As String = "AutoCAD DWG"
	Public Const MSGSINDEXdxf As String = "AutoCAD DXF"
	Public Const MSGSINDEXplot As String = "Plot Files(plt,hpg)"""
	Public Const MSGSINDEXdgn As String = "DGN"
	Public Const MSGSINDEXcgm As String = "CGM"
	Public Const MSGSINDEXOfficeFiles As String = "Office Files"
	Public Const MSGSINDEXmsword As String = "MSWord(*.doc)"
	Public Const MSGSINDEXexcel As String = "Excel(*.xls)"
	Public Const MSGSINDEXpowerpoint As String = "Powerpoint(*.ppt)"
	Public Const MSGSINDEXtext As String = "Text(*.txt)"
	Public Const MSGSINDEXacrobat As String = "Acrobat(*.pdf)"
	Public Const MSGSINDEXhtml As String = "HTML(*.htm)"
	Public Const MSGSINDEXExtractSummaries As String = "Extract Office Property Summaries"
	
	''scanner setting form
	Public Const MSGSCANForm As String = "Scanner Setings"
	Public Const MSGSCANSettingProfile As String = "Scanner Settings Profile"
	Public Const MSGSCANAutoNaming As String = "Auto Naming"
	Public Const MSGSCANdirectory As String = "Scan Directory"
	Public Const MSGSCANbasename As String = "Base Name"
	Public Const MSGSCANdriver As String = "Scanner Driver"
	Public Const MSGSCANprofile As String = "Profile"
	Public Const MSGSCANtype As String = "Scanner Type"
	Public Const MSGSCANSelect As String = "Select Scanner"
	Public Const MSGSCANAdvanced As String = "Advanced Setting"
	Public Const MSGSCANPageHandling As String = "Page Handling"
	Public Const MSGSCANnewdoc As String = "New Doc Every"
	Public Const MSGSCANpages As String = "Pages"
	Public Const MSGSCANmultipage As String = "Create Multipage"
	Public Const MSGSCANPostOption As String = "Post Scan Option"
	Public Const MSGSCANdespeckle As String = "Auto Despeckle"
	Public Const MSGSCANdeskew As String = "Auto Deskew"
	'mediacapacity form
	Public Const MSGMCPForm As String = "Open Archive - Media Capacity Planner"
	Public Const MSGMCPOther As String = "Other in Mbytes"
	Public Const MSGMCPAvailableSpace As String = "Available Space Per Disc in Mbytes"
	Public Const MSGMCPMediaOverhead As String = "Media Overhead"
	Public Const MSGMCPCloseSession As String = "Close Session in Mbytes"
	Public Const MSGMCPTrackGap As String = "Track Gap in Mbytes"
	Public Const MSGMCPRetrieval As String = "Retrieval View S/W"
	Public Const MSGMCPIndexDb As String = "Index Database %"
	Public Const MSGMCPFullText As String = "Full Text Index %"
	Public Const MSGMCPSecondary As String = "Secondary Media"
	Public Const MSGMCPDisks As String = "Disks"
	Public Const MSGMCPDrives As String = "Drives"
	Public Const MSGMCPOverallStorage As String = "Overall Storage Capacity is"
	Public Const MSGMCPStorageRequire As String = "Storage You Require"
	Public Const MSGMCPDisksRequired As String = "Disks Required"
	'login form
	Public Const MSGLOGForm As String = "Database Login"
	Public Const MSGLOGPwd As String = "Password"
	Public Const MSGLOGVerify As String = "Verify"
	'index setting form
	Public Const MSGIBSETForm As String = "Index and Build Settings"
	Public Const MSGIBSETCharacters As String = "Index Characters"
	Public Const MSGIBSETa_z As String = "A-Z,a-z"
	Public Const MSGIBSETSpecial As String = "Special Chars(!..)"
	Public Const MSGIBSETInternational As String = "International"
	Public Const MSGIBSETBuild As String = "When Building"
	Public Const MSGIBSETCopy As String = "Copy Files"
	Public Const MSGIBSETMove As String = "Move Files"
	Public Const MSGIBSETReference As String = "Reference Original Files"
	Public Const MSGIBSETCompress As String = "Compress It"
	'doc prop form
	Public Const MSGPROPProperties As String = "Document Properties"
	Public Const MSGPROPSSText As String = "Surround Search Text"
	Public Const MSGPROPName As String = "Name"
	Public Const MSGPROPLocation As String = "Location"
	Public Const MSGPROPDate As String = "Date"
	'db assistant form
	Public Const MSGASSTForm As String = "Open Archive - Database Property Assistant"
	Public Const MSGASSTDefine As String = "Define your own Database Properties"
	Public Const MSGASSTPropertyName As String = "Property Name"
	Public Const MSGASSTType As String = "Type"
	Public Const MSGASSTList As String = "List"
	Public Const MSGASSTExplore As String = "Explore"
	Public Const MSGASSTEdit As String = "Edit"
	Public Const MSGASST001 As String = "Can't Explore Titles, not a unique property"
	Public Const MSGASST002 As String = "No new field added."
	Public Const MSGASST003 As String = "Are you sure you want to add new fields to database?"
	Public Const MSGASST004 As String = "Add new fields"
	Public Const MSGASST005 As String = "Field Name has already existed"
	Public Const MSGASST006 As String = "Text"
	Public Const MSGASST007 As String = "Date"
	Public Const MSGASST008 As String = "Boolean"
	Public Const MSGASST009 As String = "Integer"
	Public Const MSGASST010 As String = "Real"
	Public Const MSGCURRENCY As String = "Currency"
	Public Const MSGASST011 As String = "Do you want to Explore "
	Public Const MSGASST012 As String = "Spaces are not allowed, try again "
	Public Const MSGASST013 As String = "Valid Characters only, try again "
	
	'add field form
	Public Const MSGADFDForm As String = "Document Properties"
	Public Const MSGADFDListed As String = "Listed"
	Public Const MSGADFDNot As String = "Not Listed"
	
	'about form
	Public Const MSGABOUTForm As String = "About "
	'Public Const MSGABOUTtitle = "Application Title"
	Public Const MSGABOUTversion As String = "Version"
	Public Const MSGAbout As String = "About"
	Public Const MSGABOUTcompany As String = "Open Archive Systems, Inc"
	Public Const MSGABOUTwww As String = "www.openarchive.com"
	Public Const MSGABOUTSystemInfo As String = "System Info..."
	Public Const MSGABOUTcredits As String = "Credits"
	
	'smart folder index form
	Public Const MSGSFIForm As String = "Open Archive Smart Folder Indexer"
	Public Const MSGSFISmartFolderIndexer As String = "Smart Folder Indexer"
	Public Const MSGSFIRootDir As String = "Root Directory"
	Public Const MSGSFILock As String = "Lock Root"
	Public Const MSGSFIPropertyDir As String = "property Directories"
	Public Const MSGSFIPropertyDesigner As String = "Property Designer"
	Public Const MSGSFITypeSetting As String = "File Type Settings"
	Public Const MSGSFIImport As String = "Import"
	Public Const MSGSFI001 As String = "Unlock Root"
	Public Const MSGSFI002 As String = "Foldexing "
	Public Const MSGSFI003 As String = "File"
	Public Const MSGSFI004 As String = "Finished Foldexing "
	Public Const MSGSFI005 As String = "Foldexer Finished"
	Public Const MSGSFI006 As String = "FileType"

	'Module1

	'OADBtools
	Public Const MsgIndexed As String = "Indexed "
	Public Const MSGOADBNoDoc As String = "No documents to index"
	Public Const MSGDBDemoMode As String = "REnew Demo version is limited to 100 records."
	Public Const MSG22 As String = "SQL Statement"
	Public Const MSG32 As String = "Data has been changed, Commit it?"
	Public Const MSG33 As String = "RollBack All changes?"
	Public Const MSG34 As String = "Can't Close with Transactions Pending!"
	Public Const MSG35 As String = "You must Close First!"
	Public Const MSG36 As String = "Open Microsoft Access Database"
	Public Const MSG49 As String = "Microsoft Access MDBs (*.mdb)|*.mdb"
	Public Const MSG50 As String = "|All Files (*.*)|*.*"
	Public Const MSG51 As String = "Select Microsoft Access Database to Compact to"
	Public Const MSG52 As String = "Encrypt Compacted Database?"
	Public Const MSG53 As String = "Compacting "
	Public Const MSG54 As String = "Open Newly Compacted Database?"
	Public Const MSG55 As String = "Select Microsoft Access Database to Create"
	Public Const MSG56 As String = "This database is missing the Property Table, "
	Public Const MSG57 As String = "Ok to generate it?"
	Public Const MSG58 As String = "Please enter the password"
	Public Const MSG59 As String = "Category"
	Public Const MSG60 As String = "Last try to enter the password"
	Public Const MSG61 As String = "error: "
	Public Const MSG63 As String = " is not a registered value of "
	Public Const MSG64 As String = "SurroundSearch creation completed"
	Public Const MSG68 As String = "This Field Already Exists"
	Public Const MSG69 As String = " error initializing field and db"
	Public Const MSG70 As String = "The field"
	Public Const MSG71 As String = " was not indexed"
	Public Const MSG72 As String = " Would you like to Index it now"
	Public Const MSG73 As String = "No matches for "
	Public Const MSG74 As String = "SQL Search "
	Public Const MSG75 As String = "MIA Search "
	Public Const MSG76 As String = " Document(s) Missing"
	Public Const MSG77 As String = "All files are valid "
	Public Const MSG78 As String = "Field already created"
	Public Const MSG79 As String = "Extracting Properties from "
	Public Const MSG80 As String = "A key was already assigned "
	Public Const MSG81 As String = "Missing In Archive"
	
	'OASurroundSearch
	Public Const MSGASS001 As String = "Starting Surround Search"
	Public Const MSGASS002 As String = " files with "
	Public Const MSGASS003 As String = " hits"
	Public Const MSGASS004 As String = "Search complete.  "
	Public Const MSGASS006 As String = "Surround Search"
	Public Const MSGASS007 As String = "Document Hits"
	Public Const MSGASS008 As String = "No Hits "
	Public Const MSGASS009 As String = "Creating New Surround Search Index"
	Public Const MSGASS010 As String = "Surround Search Indexing"
	Public Const MSGASS011 As String = "Starting index"
	Public Const MSGASS012 As String = "Opening Surround Search index"
	Public Const MSGASS013 As String = "Checking files"
	Public Const MSGASS014 As String = "Compressing Surround Search index"
	Public Const MSGASS015 As String = "Creating Surround Search index"
	Public Const MSGASS016 As String = "Indexing Complete"
	Public Const MSGASS017 As String = "Merging words into Surround Search index"
	Public Const MSGASS018 As String = "Indexing halted, index not updated"
	Public Const MSGASS019 As String = "Indexing halted, index partially updated"
	Public Const MSGASS020 As String = " documents"
	Public Const MSGASS021 As String = "Opening index"
	Public Const MSGASS022 As String = "Compressing index"
	Public Const MSGASS023 As String = "Creating index"
	Public Const MSGASS024 As String = "Indexing Complete"
	Public Const MSGASS025 As String = "Merging words into index"
	Public Const MSGASS026 As String = "in"
	Public Const MSGASS027 As String = "Open Archive Systems"
	Public Const MSGASS028 As String = "clearing index"
	Public Const MSGASS029 As String = "DWG Extracting "
	Public Const MSGASS030 As String = "Open Archive DWG/DXF Surround Search Extraction "
	Public Const MSGASS031 As String = "Indexing Cleared"
	
	'OASecurity
	Public Const MSGSECUR001 As String = "Your Site ID is: "
	Public Const MSGSECUR002 As String = "Please enter your Authorization keycode" ' or Cancel for demo mode"
	Public Const MSGSECUR002a As String = "or Select OK to enter Trial Mode"
	Public Const MSGSECUR003 As String = "Open Archive Authorization Registration"
	Public Const MSGSECUR004 As String = "Authorization code is not valid"
	'OAMain
	Public Const MSGMain001 As String = "Invalid line in ini file "
	Public Const MSGMain002 As String = "Missing ini file"
	Public Const MSGMainOpen As String = "Open echive Database"
	Public Const MSGMainNew As String = "Create New echive Database"
	Public Const MSGMainSpecify As String = "You must specify a file name"
	Public Const MSGMainNoExists As String = "File does not exist "
	Public Const MSGMainCantAddDoc As String = "You can't add a folder to a document"
	Public Const MSGMainNewProp As String = "Enter the New Property Value"
	Public Const MSGMainNewPropValue As String = "Property Value"
	
	Public Const MSGRedlineSave As String = "Save your Changes?"
	Public Const msgMainExpRedline As String = "echive Explorer with Redlining"
	Public Const msgMainOffExplorer As String = "echive Office Explorer"
	Public Const msgMainOrganizer As String = "echive Organizer"
	Public Const msgMainCapture As String = "echive Organizer with Capture"
	Public Const msgMainExistingInst As String = "echive is already running"
	Public Const msgMainDupInstance As String = "... duplicate instance."
	Public Const msgMainScanSetup As String = "You must first setup the scanner directories in scan settings"
	Public Const msgMainScanComplete As String = "Select OK when scanning is complete and ready to import"
	Public Const msgMainImportingPages As String = "Importing Pages"
	Public Const msgMainEnterSearch As String = "Enter Search Word"
	Public Const msgMainFindText As String = "Find Text"
	Public Const msgMainSaveRedlines As String = "Save Changes?"
	Public Const msgMainExploringProp As String = "Exploring Property"
	Public Const msgMainAuthorizeFailed As String = "Authorization failed"
	Public Const msgMainEchiveExplorer As String = "echive Explorer"
	Public Const msgMainechOrgOffice As String = "echive Organizer Office Edition"
	Public Const msgMainNoFileToLaunch As String = "No file selected for launching"
	Public Const msgScantoDefaults As String = "Scan into Index Defaults"
	Public Const msgMainechiveDB As String = "echive Database"
	Public Const msgadddocofft As String = "Add Document of File Type..."
	Public Const msgMainOKToDelete As String = "Are you sure you want to delete "
	Public Const msgMainClickYes As String = "Click YES to Remove this Item"
	Public Const msgMainFileNotViewable As String = "File is not viewable"
	Public Const msgMainRedlinerZoomTool As String = "Redliner Zoom Tool"
	Public Const msgMainRedlinerTool As String = "Redliner Tool: "
	Public Const msgMainNoFileToPrint As String = "No filename to Print"
	Public Const msgMainSearchPhrase As String = "Search Phrase: "
	Public Const msgMainOCRNotComplete As String = "OCR not completed "
	Public Const msgMainCreateSSIon As String = "Creating Surround Search Index on "
	Public Const msgmainbuildingssi As String = "Building Surround Search Index"
	
	
	'OAImgPro
	Public Const MSGIMG001 As String = "copied to clipboard"
	
	'new added 2-6-01
	Public Const MSGRedlineSettings As String = "Redline Settings"
	Public Const MSGRescan As String = "Rescan"
	Public Const MSGVersion As String = "Version"
	Public Const MSGUpdate As String = "Update"
	Public Const MSGMainDrop As String = "You must select a field other than FileType to drop onto"
	Public Const msgMainReadDrop As String = "can not dragdrop read only file or directory"
	Public Const MSGMainFileType As String = "FileType"
	Public Const MSGMainIsNotEnabled As String = " is not enabled "
	Public Const MSGMainNoWinApp As String = "A Windows Registered application was not found for "
	Public Const MSGDBNoTemplate As String = "The Template Database template.edb was not found "
	Public Const MSGAuthorizeFailed As String = "Authorization Failed"
	'Copy selection handler
	Public Const MSGSelectionHandler As String = "echive Selection Handler"
	Public Const MSGDrive As String = "Drive"
	Public Const msgUniqueKey As String = "Store as Unique FileName"
	Public Const MSGPreserve As String = "Preserve File Name"
	Public Const msgCopyPath As String = "Path for Copied Files"
	Public Const MSGCopy As String = "Copy"
	Public Const msgIndex As String = "Index"
	Public Const msgTitle As String = "Title"
	Public Const msgAuthor As String = "Author"
	Public Const msgCategory As String = "Category"
	Public Const msgPath As String = "Path"
	Public Const msgSelect As String = "Select"
	Public Const msgDelete As String = "Delete"
	Public Const msgRename As String = "Rename"
	Public Const msgUnselect As String = "Unselect"
	Public Const msgHelp As String = "Help"
	Public Const msgPathDoesNotExist As String = "Path Does Not Exist"
	Public Const msgStop As String = "Stop"
	Public Const msgfuzziness As String = "Fuzziness"
	Public Const msgskiptips As String = "Skip SurroundSearch Tips"
	Public Const msgstemming As String = "Stemming (ing,ed.."
	Public Const msgphonic As String = "Phonics"
	Public Const msgappend As String = "Append"
	Public Const msgfuzzy As String = "Fuzzy"
	Public Const msgword As String = "Word"
	Public Const msghitswords As String = "Hits    Words"
	Public Const msgBrowser As String = "Browser"
End Module